etl_execution:
  adapter: postgresql
  database: hidro_etl_execution
  username: tepedino
  password: tesis
  host: localhost

development:
  adapter: postgresql
  database: hidro_development
  username: tepedino
  password: tesis
  host: localhost
