# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 7) do

  create_table "activewarehouse_schema_info", :id => false, :force => true do |t|
    t.column "version", :integer
  end

  create_table "afecta_fvhc", :id => false, :force => true do |t|
    t.column "id_fenomeno_fvhc",     :string, :limit => 20,  :null => false
    t.column "id_varhidroclim_fvhc", :string, :limit => 100, :null => false
  end

  create_table "areaintereses", :force => true do |t|
    t.column "interes", :string, :limit => 50
  end

  create_table "consultas", :force => true do |t|
    t.column "usuario_id",     :integer, :null => false
    t.column "texto_pregunta", :text
  end

  create_table "consultatags", :force => true do |t|
    t.column "consulta_id", :integer,               :null => false
    t.column "tag",         :string,  :limit => 30
  end

  create_table "estacion_dimension", :force => true do |t|
    t.column "altura_est",   :float
    t.column "nombre_est",   :string
    t.column "latitud_est",  :float
    t.column "longitud_est", :float
  end

  add_index "estacion_dimension", ["altura_est"], :name => "index_estacion_dimension_on_altura_est"
  add_index "estacion_dimension", ["latitud_est"], :name => "index_estacion_dimension_on_latitud_est"
  add_index "estacion_dimension", ["longitud_est"], :name => "index_estacion_dimension_on_longitud_est"
  add_index "estacion_dimension", ["nombre_est"], :name => "index_estacion_dimension_on_nombre_est"

  create_table "estaciones", :force => true do |t|
    t.column "latitud",     :float,                  :null => false
    t.column "longitud",    :float,                  :null => false
    t.column "pais",        :string,  :limit => 80,  :null => false
    t.column "informacion", :string,  :limit => 300, :null => false
    t.column "nombre",      :string,  :limit => 100
    t.column "estado_id",   :integer,                :null => false
    t.column "codigo_omm",  :string,  :limit => 100
    t.column "altura",      :integer
  end

  create_table "estados", :force => true do |t|
    t.column "nombre", :string, :limit => 40, :null => false
  end

  create_table "fenomeno_meteorologico", :id => false, :force => true do |t|
    t.column "nombre_f",       :string, :limit => 20,  :null => false
    t.column "descrip_f",      :string, :limit => 150
    t.column "lugar_geo_f",    :string, :limit => 200
    t.column "primera_obs_f",  :date
    t.column "periodicidad_f", :string, :limit => 15
  end

  create_table "incide_tof", :id => false, :force => true do |t|
    t.column "id_tipo_objeto_tof", :string, :limit => 20, :null => false
    t.column "id_fenomeno_tof",    :string, :limit => 20, :null => false
  end

  create_table "medidavarhc_facts", :force => true do |t|
    t.column "tiempo_id",          :integer, :null => false
    t.column "estacion_id",        :integer, :null => false
    t.column "unidad_id",          :integer, :null => false
    t.column "nivelagregacion_id", :integer, :null => false
    t.column "variable_id",        :integer, :null => false
    t.column "valor_m",            :float,   :null => false
    t.column "observacion_m",      :string
  end

  add_index "medidavarhc_facts", ["estacion_id"], :name => "index_medidavarhc_facts_on_estacion_id"
  add_index "medidavarhc_facts", ["nivelagregacion_id"], :name => "index_medidavarhc_facts_on_nivelagregacion_id"
  add_index "medidavarhc_facts", ["tiempo_id"], :name => "index_medidavarhc_facts_on_tiempo_id"
  add_index "medidavarhc_facts", ["unidad_id"], :name => "index_medidavarhc_facts_on_unidad_id"
  add_index "medidavarhc_facts", ["variable_id"], :name => "index_medidavarhc_facts_on_variable_id"

  create_table "medio", :id => false, :force => true do |t|
    t.column "nombre_med",          :string, :limit => 100, :null => false
    t.column "descripcion_med",     :string, :limit => 400
    t.column "propiedades_med",     :string, :limit => 400
    t.column "id_tipo_instrumento", :string, :limit => 100
  end

  create_table "metadatos_desc", :primary_key => "id_metadesc", :force => true do |t|
    t.column "tipo_variable",        :string, :limit => 50,  :null => false
    t.column "codigo_estacion_muni", :string, :limit => 15,  :null => false
    t.column "variable",             :string, :limit => 50,  :null => false
    t.column "granularidad",         :string, :limit => 200, :null => false
    t.column "fecha_inicio",         :date,                  :null => false
    t.column "fecha_fin",            :date,                  :null => false
  end

  create_table "metadatos_rowids", :id => false, :force => true do |t|
    t.column "id_descriptor", :integer, :null => false
    t.column "row_id_medida", :integer, :null => false
  end

  create_table "nivelagregacion_dimension", :force => true do |t|
    t.column "nivel_agregacion", :string
  end

  add_index "nivelagregacion_dimension", ["nivel_agregacion"], :name => "index_nivelagregacion_dimension_on_nivel_agregacion"

  create_table "periodo_operacion", :id => false, :force => true do |t|
    t.column "estacion_id_po",  :integer, :null => false
    t.column "fecha_inicio_po", :date,    :null => false
    t.column "fecha_fin_po",    :date,    :null => false
  end

  create_table "puede_medir_vtins", :id => false, :force => true do |t|
    t.column "id_varhidroclim_vtins", :string, :limit => 100, :null => false
    t.column "id_tipo_ins_vtins",     :string, :limit => 20,  :null => false
  end

  create_table "se_asocia_vhcto", :id => false, :force => true do |t|
    t.column "id_varhidroclim_vhcto", :string, :limit => 100, :null => false
    t.column "id_tipo_objeto_vhcto",  :string, :limit => 20,  :null => false
  end

  create_table "se_mide_vuni", :id => false, :force => true do |t|
    t.column "id_varhidroclim_vuni", :string,  :limit => 100, :null => false
    t.column "id_unid_vuni",         :integer,                :null => false
  end

  create_table "se_observa", :id => false, :force => true do |t|
    t.column "estacion_id", :integer,                :null => false
    t.column "nombre_hc",   :string,  :limit => 100, :null => false
  end

  create_table "se_relaciona_vseto", :id => false, :force => true do |t|
    t.column "id_varsocioe_vseto",   :string, :limit => 100, :null => false
    t.column "id_tipo_objeto_vseto", :string, :limit => 20,  :null => false
  end

  create_table "servicios", :force => true do |t|
    t.column "nombre",      :string,  :limit => 30,  :null => false
    t.column "descripcion", :string,  :limit => 200, :null => false
    t.column "habilitado",  :boolean,                :null => false
    t.column "autor",       :string,  :limit => 30,  :null => false
    t.column "usuario_id",  :integer,                :null => false
    t.column "url_wsdl",    :string,  :limit => 100
    t.column "url_owls",    :string,  :limit => 100
    t.column "tags",        :string
  end

  create_table "simple_captcha_data", :force => true do |t|
    t.column "key",        :string, :limit => 40, :null => false
    t.column "value",      :string, :limit => 6
    t.column "created_at", :date
    t.column "updated_at", :date
  end

  create_table "table_reports", :force => true do |t|
    t.column "title",                 :string
    t.column "cube_name",             :string,   :null => false
    t.column "column_dimension_name", :string
    t.column "column_hierarchy",      :string
    t.column "column_constraints",    :text
    t.column "column_stage",          :integer
    t.column "column_param_prefix",   :string
    t.column "row_dimension_name",    :string
    t.column "row_hierarchy",         :string
    t.column "row_constraints",       :text
    t.column "row_stage",             :integer
    t.column "row_param_prefix",      :string
    t.column "fact_attributes",       :text
    t.column "created_at",            :datetime
    t.column "updated_at",            :datetime
  end

  create_table "tiempo_dimension", :force => true do |t|
    t.column "tiempo",        :date
    t.column "dia",           :integer
    t.column "anio",          :integer
    t.column "mes",           :integer
    t.column "hora",          :time
    t.column "unidad_t",      :string
    t.column "observacion_t", :string
  end

  add_index "tiempo_dimension", ["anio"], :name => "index_tiempo_dimension_on_anio"
  add_index "tiempo_dimension", ["dia"], :name => "index_tiempo_dimension_on_dia"
  add_index "tiempo_dimension", ["hora"], :name => "index_tiempo_dimension_on_hora"
  add_index "tiempo_dimension", ["mes"], :name => "index_tiempo_dimension_on_mes"
  add_index "tiempo_dimension", ["observacion_t"], :name => "index_tiempo_dimension_on_observacion_t"
  add_index "tiempo_dimension", ["tiempo"], :name => "index_tiempo_dimension_on_tiempo"
  add_index "tiempo_dimension", ["unidad_t"], :name => "index_tiempo_dimension_on_unidad_t"

  create_table "tipo_instrumento", :id => false, :force => true do |t|
    t.column "nombre_ti",           :string, :limit => 100, :null => false
    t.column "tipo_ti",             :string, :limit => 1
    t.column "tipo_registrador_ti", :string, :limit => 2
    t.column "descripcion_ti",      :string, :limit => 400
    t.column "restriccion_ti",      :string, :limit => 200
  end

  create_table "tipo_objeto", :id => false, :force => true do |t|
    t.column "nombre_generico_to", :string, :limit => 20,  :null => false
    t.column "clase_to",           :string, :limit => 1
    t.column "descrip_to",         :string, :limit => 150
    t.column "alcance_geo_to",     :string, :limit => 200
  end

  create_table "unidad", :id => false, :force => true do |t|
    t.column "id_unid",       :integer,                :null => false
    t.column "nombre_unid",   :string,  :limit => 100, :null => false
    t.column "acronimo_unid", :string,  :limit => 20
  end

  create_table "unidad_dimension", :force => true do |t|
    t.column "unidad_medida_u", :string
    t.column "observacion_u",   :string
  end

  add_index "unidad_dimension", ["observacion_u"], :name => "index_unidad_dimension_on_observacion_u"
  add_index "unidad_dimension", ["unidad_medida_u"], :name => "index_unidad_dimension_on_unidad_medida_u"

  create_table "usuarios", :force => true do |t|
    t.column "login",                     :string, :limit => 40,  :null => false
    t.column "crypted_password",          :string, :limit => 40,  :null => false
    t.column "salt",                      :string, :limit => 40
    t.column "nombre",                    :string, :limit => 20,  :null => false
    t.column "apellido",                  :string, :limit => 20,  :null => false
    t.column "tipo",                      :string, :limit => 14,  :null => false
    t.column "sexo",                      :string, :limit => 1,   :null => false
    t.column "fecha_nacimiento",          :date,                  :null => false
    t.column "fecha_registro",            :date,                  :null => false
    t.column "telefono",                  :string, :limit => 16
    t.column "nivel_estudio",             :string, :limit => 25,  :null => false
    t.column "campo_trabajo",             :string, :limit => 30,  :null => false
    t.column "direccion_hab",             :string, :limit => 200
    t.column "email_address",             :string, :limit => 30
    t.column "remember_token",            :string
    t.column "remember_token_expires_at", :date
  end

  add_index "usuarios", ["login"], :name => "uk_usuarios", :unique => true

  create_table "usuarios_intereses", :force => true do |t|
    t.column "usuario_id",      :integer, :null => false
    t.column "areainterese_id", :integer, :null => false
  end

  create_table "variable_dimension", :force => true do |t|
    t.column "observacion_hc", :string
    t.column "nombre_hc",      :string
  end

  add_index "variable_dimension", ["nombre_hc"], :name => "index_variable_dimension_on_nombre_hc"
  add_index "variable_dimension", ["observacion_hc"], :name => "index_variable_dimension_on_observacion_hc"

  create_table "variable_hidroclimatica", :id => false, :force => true do |t|
    t.column "nombre_hc",      :string, :limit => 100, :null => false
    t.column "tipo_hc",        :string, :limit => 1
    t.column "descripcion_hc", :string, :limit => 400
    t.column "acumulada_hc",   :string, :limit => 1
  end

  create_table "variable_socioeconomica", :id => false, :force => true do |t|
    t.column "nombre_vse",      :string, :limit => 100, :null => false
    t.column "descripcion_vse", :string, :limit => 400
  end

  create_table "vinculotags", :force => true do |t|
    t.column "usuario_id",  :integer,                :null => false
    t.column "vinculo",     :string,  :limit => 100, :null => false
    t.column "tag",         :string,  :limit => 300, :null => false
    t.column "descripcion", :string,  :limit => 200, :null => false
    t.column "oficial",     :string,  :limit => 2,   :null => false
  end

end
